name: Reporting Bug
description: Report us the issue, and leave it to us! 🤗
title: "Bug: "
labels: "bug"
assignees: "Leref"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Fill in the blanks by following the steps. 🙌

        Please **ensure the following** before reporting a bug:
        ✅ I am using the latest versions of aoi.js (v6.6.1).
        ✅ I am using a version of NodeJS (v20.5.1 or newer).
      
  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      description: Please select a type of bug you want to report.
      options:
        - Function 
        - Callback 
        - Handler 
        - Extensions 
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: Bugged Function
      render: js
      description: Please type usage of your code
      placeholder: |
        module.exports = {
          name: "ping",
          type: 'interaction',
          prototype: 'slash',
          code: `
          $sendMessage[Hello?]
          `
        }
    validations:
      required: true
               
  - type: textarea
    id: excepted
    attributes:
      label: Excepted Output
      description: Please describe your expectations the code you have tried.
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/AkaruiDevelopment/aoi.js/blob/v5/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct 
          required: true
