name: publish-dev
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Deprecate old versions
        run: npm deprecate aoi.js@"~7.0.0-dev" "This is no longer supported" || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(git rev-parse --short HEAD).$(date +%s)
          npm publish --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
